#!/bin/bash

cd "$(dirname "$0")/.." || exit 1

latest_ruby="$(ruby -e "require 'yaml'; puts YAML.load_file('.travis.yml')['rvm'][0]")"

if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_RUBY_VERSION" == "$latest_ruby" ]; then
  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  chmod +x ./cc-test-reporter
  ./cc-test-reporter after-build --exit-code "$TRAVIS_TEST_RESULT"
fi
